version: "3.9"
services:
  web:
    build: .
    container_name: ad_api_web
    ports:
      - "7000:7000"  # Formato: "HOST_PORT:CONTAINER_PORT"
    env_file:
      - .env
    environment:
      - PORT=7000  # Garantir que a porta do container seja 8000
    restart: unless-stopped
    # Se quiser montar o c√≥digo local para hot-reload (desative gunicorn e use runserver)
    # volumes:
    #   - .:/app
